#
#
#version: '3'
#services:
#  db:
#    image: postgres:latest  # Official PostgreSQL image
#    restart: always
#    container_name: postgres-db
#    environment:
#      POSTGRES_DB: valuemart-dev
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data  # Persist PostgreSQL data
#
#  value-mart-shop:
#    image: timmybot/shop:2.0
#    container_name: the-shop
#    ports:
#      - "9010:9010"
#    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/valuemart
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#
#volumes:
#  db-data:
